site_name: 17648 Sensor Based Systems

nav:
  - Home: index.md
  - Course Software: software.md
  - Course Hardware: coursehardware.md
  - Course Project: project.md
  - Sensor Basics: sensorbasics.md
  - Digital Twins: digitaltwins.md
  - About: syllabus.md
theme: readthedocs
